# Generated by Django 3.0.8 on 2022-01-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220110_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdb',
            old_name='zip_code',
            new_name='zip',
        ),
    ]
