# Generated by Django 3.0.8 on 2022-01-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220110_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
