# Generated by Django 3.0.8 on 2022-01-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220110_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
